include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    always_declare_return_types: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: false
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    annotate_overrides: true
    unawaited_futures: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    always_use_package_imports: true

formatter:
  page_width: 120
  trailing_commas: preserve

analyzer:
  exclude:
    - '**/*.g.dart'
