name: news_test
description: "Starter project for the Flutter news test task."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  # Routing
  go_router: ^15.1.2

  # Network
  dio: ^5.7.0
  dio_pretty_logger: ^1.0.4
  retrofit: ^4.9.2

  # UI
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.4

  # Utils
  json_annotation: ^4.11.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Analysis
  flutter_lints: ^6.0.0

  # Generators
  build_runner: ^2.13.1
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
